spring.application.name=navbackend
server.port=8080

# GraphHopper Configuration
osm.pbf.path=classpath:osm/schwaben.osm.pbf
osm.cache.dir=target/graphhopper-cache
osm.vehicles.dir=classpath:osm/vehicles

# Optional: directory where preprocessed graph chunks and cache are stored.
# If empty, a `graph-chunks` folder next to the running JAR is used.
graph.chunks.path=


# Logging
logging.level.com.patriot.nav=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.graphhopper=INFO
logging.level.org.mapdb=DEBUG